### ISSUE TITLE
Le tableau de bord n'affiche pas la 2nde récompense

### ISSUE THREAD

**Issue by kevinvennitti** [ludomuse/Ludomuse#10]
La deuxième récompense de la production transversale ne s'affiche pas dans le tableau de bord à la fin des défis (il n'y a que le sucre, et pas la seconde récompense).

**Comment by Babouchot** [comment]
Je crois que c'est le problème dont on avait parlé sur Trello où je disais qu'il me manquait les contenus graphiques non ?

**Comment by Babouchot** [comment]
Je crois que c'est le problème dont on avait parlé sur Trello où je disais qu'il me manquait les contenus graphiques non ?
