### ISSUE TITLE
Désactiver les événements Touch sur les boutons d'un quiz

### ISSUE THREAD

**Issue by kevinvennitti** [ludomuse/Ludomuse#15]
Lorsqu'un quiz est remporté (la ou les bonnes réponses ont été trouvées), il faut verrouiller les choix du quiz en DisableEvent les Touch.

**Comment by Babouchot** [comment]
N'a été ajouté que pour le premier quizz de Nantes.json
Il restera à ajouter le callback dans les autres jeux
